"""Composite Financial Health Score & Executive Rationale Aggregator (Module 8.3).

Responsible for:
1. Aggregating 5 dimensional scores using weighted average:
   - Growth: 20% (0.20)
   - Profitability: 25% (0.25)
   - Liquidity: 20% (0.20)
   - Leverage: 20% (0.20)
   - Cash Flow: 15% (0.15)
2. Compiling executive rating category: 'Strong', 'Stable', 'Moderate', 'Fragile', or 'Distressed'.
3. Generating human-readable executive summary rationales and compiling dimension deductions.
4. Appending standard regulatory disclaimer string to ensure compliance.
"""

from typing import Dict, List, Optional
from pydantic import BaseModel, Field

from app.analytics.health_growth_profit import DimensionScoreDTO


DEFAULT_REGULATORY_DISCLAIMER: str = ( #Standard regulatory compliance disclaimer clarifying algorithmic score nature
    "This is an indicative analytical score, not a certified credit rating or investment recommendation. "
    "Algorithmic scores are generated by deterministic heuristics for research and educational purposes only."
)


class CorporateHealthReportDTO(BaseModel): #Final composite report DTO containing overall score (0-100), rating tier, dimension breakdown, rationales, and disclaimer
    """Data Transfer Object encapsulating overall corporate health score, dimensional breakdown, and rationales."""

    overall_score: float = Field( #Overall composite financial health score bounded between 0.0 and 100.0
        ...,
        ge=0.0,
        le=100.0,
        description="Overall composite financial health score bounded between 0.0 and 100.0.",
    )
    rating_category: str = Field( #Qualitative corporate health tier: 'Strong', 'Stable', 'Moderate', 'Fragile', or 'Distressed'
        ...,
        description="Qualitative corporate health tier: 'Strong', 'Stable', 'Moderate', 'Fragile', or 'Distressed'.",
    )
    dimension_scores: Dict[str, DimensionScoreDTO] = Field( #Breakdown map of scores across all 5 dimensions
        ...,
        description="Map of dimensional score DTOs across growth, profitability, liquidity, leverage, and cash flow.",
    )
    summary_rationales: List[str] = Field( #Executive summary bullets detailing strengths, vulnerabilities, and specific deductions
        default_factory=list,
        description="Executive summary bullets detailing strengths, vulnerabilities, and specific deductions.",
    )
    disclaimer: str = Field( #Mandatory regulatory disclaimer
        default=DEFAULT_REGULATORY_DISCLAIMER,
        description="Mandatory regulatory disclaimer regarding algorithmic analytical scoring.",
    )


class HealthScoreAggregator: #Aggregates dimensional financial scores into a composite corporate health score and executive report
    """Aggregates dimensional financial scores into a composite corporate health score and executive report.

    Technical Tasks:
    1. Weighted Score Aggregator (100% total weight across 5 dimensions):
       - Growth: 20% (0.20)
       - Profitability: 25% (0.25)
       - Liquidity: 20% (0.20)
       - Leverage: 20% (0.20)
       - Cash Flow: 15% (0.15)
    2. Executive Rationale Generator:
       - Determines rating category: Strong (>=80), Stable (>=65), Moderate (>=50), Fragile (>=35), Distressed (<35).
       - Synthesizes key operational strengths and structural vulnerabilities.
       - Appends standard regulatory compliance disclaimer.
    """

    # Weights summing to 100% (1.00)
    WEIGHT_GROWTH: float = 0.20 #Growth dimension weight: 20%
    WEIGHT_PROFIT: float = 0.25 #Profitability dimension weight: 25%
    WEIGHT_LIQUIDITY: float = 0.20 #Liquidity dimension weight: 20%
    WEIGHT_LEVERAGE: float = 0.20 #Leverage & Solvency dimension weight: 20%
    WEIGHT_CASH_FLOW: float = 0.15 #Cash Flow Quality dimension weight: 15%

    def __init__(self, disclaimer: Optional[str] = None) -> None: #Initialize aggregator with optional custom disclaimer
        """Initializes the health score aggregator.

        Args:
            disclaimer: Optional custom regulatory disclaimer text.
        """
        self.disclaimer = disclaimer or DEFAULT_REGULATORY_DISCLAIMER

    @staticmethod
    def determine_rating(score: float) -> str: #Maps overall composite score (0-100) to executive rating category
        """Maps an overall composite score (0-100) to a qualitative rating tier.

        Tiers:
        - >= 80.0: Strong
        - >= 65.0: Stable
        - >= 50.0: Moderate
        - >= 35.0: Fragile
        - < 35.0: Distressed
        """
        if score >= 80.0: #80-100: Pristine corporate balance sheet & strong operating metrics
            return "Strong"
        if score >= 65.0: #65-79: Resilient fundamentals with manageable debt obligations
            return "Stable"
        if score >= 50.0: #50-64: Fair viability with moderate leverage or margin squeeze
            return "Moderate"
        if score >= 35.0: #35-49: Elevated risk from negative working capital or declining profits
            return "Fragile"
        return "Distressed" #Under 35: Severe distress, high default risk or balance sheet impairment

    def _generate_rationales( #Generates bullet-point executive insights explaining the score breakdown
        self,
        overall_score: float,
        rating: str,
        dim_map: Dict[str, DimensionScoreDTO],
    ) -> List[str]:
        """Generates clear, executive-level synthesis bullets explaining the corporate health score."""
        rationales: List[str] = [] #Collector for bullet-point rationales

        # 1. Headline summary rationale
        if rating == "Strong":
            rationales.append(
                f"Robust Financial Health ({overall_score:.2f}/100 - Strong): Company demonstrates stellar operational and structural fundamentals across core financial dimensions."
            )
        elif rating == "Stable":
            rationales.append(
                f"Stable Financial Health ({overall_score:.2f}/100 - Stable): Company maintains resilient fiscal health with sustainable operations and manageable balance sheet obligations."
            )
        elif rating == "Moderate":
            rationales.append(
                f"Moderate Financial Health ({overall_score:.2f}/100 - Moderate): Company exhibits fair operational viability, but key areas such as debt service or margin pressures require prudent monitoring."
            )
        elif rating == "Fragile":
            rationales.append(
                f"Fragile Financial Condition ({overall_score:.2f}/100 - Fragile): Elevated vulnerabilities observed across multiple operating dimensions; working capital or bottom-line contraction poses financial strain."
            )
        else:
            rationales.append(
                f"Distressed Financial Condition ({overall_score:.2f}/100 - Distressed): Severe financial distress indicators present, reflecting critical insolvency, heavy debt overhang, or operational cash burn."
            )

        # 2. Key Strengths (Dimensions with score >= 80)
        strengths = [ #Highlight dimensions scoring 80+ as competitive advantages
            f"{name.replace('_', ' ').title()} ({dto.score:.1f} pts - {dto.grade})"
            for name, dto in dim_map.items()
            if dto.score >= 80.0
        ]
        if strengths:
            rationales.append(f"Core Strengths: {', '.join(strengths)}.")

        # 3. Key Vulnerabilities (Dimensions with score < 50)
        vulnerabilities = [ #Highlight dimensions scoring below 50 as financial warning signs
            f"{name.replace('_', ' ').title()} ({dto.score:.1f} pts - {dto.grade})"
            for name, dto in dim_map.items()
            if dto.score < 50.0
        ]
        if vulnerabilities:
            rationales.append(f"Areas of Vulnerability: {', '.join(vulnerabilities)}.")

        # 4. Critical Deductions (Detailed rationales from dimensions with penalties)
        for name, dto in dim_map.items(): #Append all individual deduction reasons across dimensions
            dim_label = name.replace("_", " ").title()
            for deduction in dto.deductions:
                rationales.append(f"[{dim_label}] {deduction}")

        return rationales

    def aggregate( #Main function: computes weighted score across all 5 dimensions and builds complete report
        self,
        growth: DimensionScoreDTO,
        profit: DimensionScoreDTO,
        liquidity: DimensionScoreDTO,
        leverage: DimensionScoreDTO,
        cash_flow: DimensionScoreDTO,
    ) -> CorporateHealthReportDTO:
        """Aggregates dimensional scores into final explainable corporate health report.

        Args:
            growth: Growth DimensionScoreDTO (20% weight).
            profit: Profitability DimensionScoreDTO (25% weight).
            liquidity: Liquidity DimensionScoreDTO (20% weight).
            leverage: Leverage DimensionScoreDTO (20% weight).
            cash_flow: Cash Flow Quality DimensionScoreDTO (15% weight).

        Returns:
            CorporateHealthReportDTO: Complete deterministic corporate health report.

        Raises:
            TypeError: If any dimension argument is not an instance of DimensionScoreDTO.
        """
        for arg, name in [ #Validate all 5 inputs are valid DimensionScoreDTO instances
            (growth, "growth"),
            (profit, "profit"),
            (liquidity, "liquidity"),
            (leverage, "leverage"),
            (cash_flow, "cash_flow"),
        ]:
            if not isinstance(arg, DimensionScoreDTO):
                raise TypeError(f"Argument '{name}' must be an instance of DimensionScoreDTO, got {type(arg).__name__}.")

        # Task 1: Weighted Score Calculation (sum of each dimension multiplied by its weight)
        overall = (
            self.WEIGHT_GROWTH * growth.score #20% Growth
            + self.WEIGHT_PROFIT * profit.score #25% Profitability
            + self.WEIGHT_LIQUIDITY * liquidity.score #20% Liquidity
            + self.WEIGHT_LEVERAGE * leverage.score #20% Leverage
            + self.WEIGHT_CASH_FLOW * cash_flow.score #15% Cash Flow Quality
        )
        overall = round(max(0.0, min(100.0, overall)), 2) #Round and clamp composite score between 0 and 100

        # Task 2: Executive Rationale Generator
        rating = self.determine_rating(overall) #Determine qualitative tier (Strong, Stable, Moderate, Fragile, Distressed)

        dim_map: Dict[str, DimensionScoreDTO] = { #Assemble dictionary of dimension scores
            "growth": growth,
            "profitability": profit,
            "liquidity": liquidity,
            "leverage": leverage,
            "cash_flow": cash_flow,
        }

        rationales = self._generate_rationales(overall, rating, dim_map) #Generate synthesis bullets and deductions

        return CorporateHealthReportDTO( #Package and return complete corporate health report
            overall_score=overall,
            rating_category=rating,
            dimension_scores=dim_map,
            summary_rationales=rationales,
            disclaimer=self.disclaimer,
        )
