"""Negative-Constraint System Prompt Formulation for Financial RAG (Module 4.2).

Responsible for:
1. Formulating system prompt commanding the model to answer ONLY from context
   and state failure if data is absent (zero extrapolation, strict groundedness).
2. Defining deterministic fallback token string:
   "The provided document does not contain sufficient information to answer this query."
3. Assembling OpenAI-compatible message lists pairing system instructions with user context.
"""

from typing import Dict, List


class FinancialSystemPrompts:
    """System prompts and message formatters enforcing strict factual compliance in financial Q&A."""

    FALLBACK_RESPONSE: str = (
        "The provided document does not contain sufficient information to answer this query."
    )

    RAG_SYSTEM_PROMPT: str = (
        "You are an expert Financial Document Intelligence Assistant designed to provide rigorous, "
        "factually grounded analysis of financial disclosures, annual reports, and SEC filings.\n\n"
        "STRICT GROUNDING & NEGATIVE CONSTRAINTS:\n"
        "1. Answer the user's question SOLELY and EXCLUSIVELY using the verified information provided "
        "inside the <context>...</context> XML block.\n"
        "2. Do NOT extrapolate, speculate, infer unstated trends, or introduce external knowledge not "
        "present in the context.\n"
        "3. Every factual claim, figure, ratio, and monetary amount must be directly supported by the context.\n"
        "4. When citing information, always reference the document and page number provided in the context "
        "headers (e.g., [Doc: <id>, Page: <n>]).\n"
        "5. If the provided context does not contain direct, sufficient, or unequivocal evidence to answer the "
        "question, you MUST output the exact fallback sentence verbatim and nothing else:\n"
        f'"{FALLBACK_RESPONSE}"\n'
        "6. Do NOT attempt to partially guess or provide speculative answers if the data is incomplete or missing."
    )

    @classmethod
    def get_grounded_prompt(
        cls,
        user_query: str,
        context_block: str,
    ) -> List[Dict[str, str]]:
        """Returns OpenAI-compatible messages list with system instructions and user context.

        Args:
            user_query: The question or analytical prompt submitted by the user.
            context_block: Delimited XML context block generated by PromptBuilder.

        Returns:
            List[Dict[str, str]]: OpenAI chat completion messages payload.

        Raises:
            ValueError: If user_query is empty or whitespace.
            TypeError: If user_query or context_block are not strings.
        """
        if not isinstance(user_query, str):
            raise TypeError("user_query must be a string.")

        if not isinstance(context_block, str):
            raise TypeError("context_block must be a string.")

        cleaned_query = user_query.strip()
        if not cleaned_query:
            raise ValueError("user_query cannot be empty or whitespace.")

        user_content = f"{context_block.strip()}\n\nQuestion: {cleaned_query}"

        return [
            {
                "role": "system",
                "content": cls.RAG_SYSTEM_PROMPT,
            },
            {
                "role": "user",
                "content": user_content,
            },
        ]
